Repository jitacm/30-days-cpp_-Bus_reservation-, pull requests merged in 2025-08, with the labels that each got.

#2 Cancel Reservation Functionality Implemented #1
  bus_reservation_partial.cpp
Labels: bug, 30DaysDevChallenge, JITACM, Level-2

#4 Added support for multi-word input in Bus Reservation System
  bus_reservation_partial.cpp
Labels: 30DaysDevChallenge, JITACM, Level-2, feature

#8 Fix Input Handling for Full Passenger Names and Prevent Duplicate Bus…
  README.md
  bus_reservation_partial.cpp
Labels: bug, 30DaysDevChallenge, JITACM, Level-3

#26 Fix bugs, improve menu flow, and add user authentication
  bus-reservation-system/bus.exe
  bus-reservation-system/bus_reservation_partial.cpp
  bus-reservation-system/main.cpp
  bus-reservation-system/main.exe
  bus-reservation-system/user.cpp
  bus-reservation-system/user.h
  bus_reservation_partial.exe
Labels: 30DaysDevChallenge, JITACM, Level-3, feature

#30 Implement advanced search and booking management
  bus-reservation-system/main.cpp
Labels: 30DaysDevChallenge, JITACM, Level-1, feature

#32 Add Admin Features: Passenger List and Driver Search
  README.md
  bus-reservation-system/main.cpp
Labels: 30DaysDevChallenge, Level-4, feature

#40 Feature: Add Passenger List Export, Bus Search, and Show All Buses Functionality
  .vscode/settings.json
  bus-reservation-system/bus_reservation_partial.cpp
Labels: 30DaysDevChallenge, JITACM, Level-3, feature
